-- 0014：白名單加上「這個人看不看得到足跡地圖」。
--
-- 訪客那一層早就有開關了（AppSetting.guest_can_view_map，預設關），但成員一律
-- 看得到 —— 只要在白名單上，照片座標與家人的 GPS 軌跡就全部攤開。足跡比照片更敏感：
-- 它是「誰、什麼時候、在哪裡」的連續紀錄，而白名單上不是每個人都該看到每個人的行蹤。
--
-- ## 粒度沿用既有的兩套，不另創第三套
--
--   can_view_map        每人一欄（就是這裡）。同 0010／0013 的理由：站長要能單獨關掉某一個人
--   guest_can_view_map  全站一個，放 AppSetting。已經存在，這次不動
--
-- ## 預設 1（開）
--
-- 跟 can_comment／can_view_comments 一樣。現況就是所有成員都看得到，預設 0 等於
-- 這次 migration 一套下去全家人的地圖同時消失，那是改壞不是改對。
--
-- ## 不吃 can_manage_others 的短路
--
-- 「管不管得動別人的相簿」跟「該不該看到家人的行蹤」是兩回事，跟留言那兩欄同一個道理。
-- 只有站長永遠是開的（程式裡 isOwner 直接放行，不看這一欄）。

ALTER TABLE User ADD COLUMN can_view_map INTEGER NOT NULL DEFAULT 1;
