-- 每個人的自訂頭像。
--
-- 兩個用途共用同一張圖（使用者定調）：留言區的圓形頭像，以及地圖上坐在小車上的
-- 那顆大頭。所以圖是**去背 PNG／WebP**（保 alpha）—— 沒去背的圖前端會自動套
-- 圓形遮罩再上傳，永遠不會是一塊方照片貼在車上。
--
-- 存的是 R2 物件的**檔名**，不是完整鍵也不是網址：
--   R2 鍵  = 'avatars/' || avatar_key
--   對外   = {origin}/api/users/avatar/{avatar_key}
-- 檔名帶亂數尾碼（`<uid>-<12 碼十六進位>.webp`），這是它唯一的護欄 —— 頭像端點在
-- 進站閘門的白名單裡（<img src> 帶不了 Authorization，跟照片同一個理由），
-- 猜不到檔名就打不到。**不要改成 /api/users/:id/avatar 那種可枚舉的形式。**
-- 換頭像 = 換一個新檔名，順便讓 immutable 快取自動失效。
--
-- NULL = 沒設過。留言區退回「名字首字 + track_color 的圓」，
-- 地圖上坐的是飛碟退休後留下的那顆小外星人頭。
ALTER TABLE User ADD COLUMN avatar_key TEXT;
