-- 0020：單張照片／影片的「不開放」。
--
-- 勾起來之後，**只有可管理全站內容的人**（站長與 can_manage_others=1）看得到
-- 這一格；其餘成員與訪客眼中它整個不存在 —— 不是打馬賽克、不是點不開，
-- 是相簿頁、搜尋、首頁預覽、足跡地圖全部都沒有它。
--
-- ## 為什麼是新的一欄，不是沿用 geo_private
--
-- geo_private 管的是「這一張的**座標**不要出現在地圖上」，照片本身照樣看得到。
-- 這一欄管的是照片本身。兩件事互不隸屬（一張不開放的照片當然也不出現在地圖上，
-- 但反過來不成立），塞進同一欄會讓「只想藏座標」變成「整張藏起來」。
--
-- ## DEFAULT 0 + NOT NULL
--
-- 現有的每一列都是開放的，預設值讓這次 migration 不必回頭 UPDATE 任何一列
-- （prod 上是好幾千列，[[free-tier-is-top-priority]]）。
-- NOT NULL 是為了讓 `restricted = 0` 這個條件在舊列上也成立 —— 可為 NULL 的話
-- 就得到處寫 `IS NOT 1`（見 CLAUDE.md 那條 geo_source 的坑），漏一處就是漏光。
--
-- ## 沒有另外開索引
--
-- 讀取端一律是「已經有 album_id / FTS / 標籤把範圍縮到幾百列」之後再加一個
-- `AND restricted = 0` 的過濾，不是拿它當入口條件。多一個索引只是多一份寫入
-- 成本與儲存。
--
-- ⚠️ 大圖與影片位元組那兩條路由（/api/photos/:id/full、/video）走的是簽章網址
--    `?mt=`，那張票**不帶身分**。所以 mt 分成兩種粒度（見後端 mintMediaToken）：
--    一般的那張進不了不開放的照片，可管理全站內容的人拿到的是升級版的那張。

ALTER TABLE Photo ADD COLUMN restricted INTEGER NOT NULL DEFAULT 0;
