-- 0027：訪客看得到哪幾本相簿
--
-- ## 為什麼是相簿上的一欄，不是 AppSetting 裡的一串 id
--
-- 過濾**一定要寫在 SQL 的 WHERE 裡**（同 restricted、同 map_private）：撈回來
-- 再挑等於那幾本相簿的名字、封面、預覽圖都已經出現在回應裡了。要在 WHERE 裡
-- 比就得是一個欄位；存成 AppSetting 的一串 id 只能拼成 `IN (…)`，而 D1 的
-- 綁定參數上限是 100，相簿一多就直接 500。
--
-- ## DEFAULT 0＝白名單（使用者 2026-09-07 拍板）
--
-- 「預設看不到，逐本開放」。代價是**這支 migration 一套下去，訪客眼中整個站
-- 就是空的**，直到站長進 /admin 勾第一本；而且**之後新建的相簿一律是關的**，
-- 建完要自己去勾。反過來（DEFAULT 1）的代價是每建一本新相簿就默默對訪客公開
-- 一次，忘記關才是那個會出事的方向。
--
-- ⚠️ 這一欄管的**只有訪客**。成員（Google 登入、白名單內）看得到全部，
--    跟 map_private／restricted 是三件互不相干的事。
ALTER TABLE Album ADD COLUMN guest_visible INTEGER NOT NULL DEFAULT 0;
